device: 'cuda'  # or 'cpu' if you do not have a GPU
experiment_dir: './experiments/'

data:
  path: 'D:/Ziwei/Github/data/data.h5'

loader:
  batch_size: 32
  shuffle: True

model:
  name: 'ContrastiveVAE'
  kwargs:
    input_dim: 3072  # This is 1024*3
    latent_dim: 128
    projection_dim: 64
    k: 20
    emb_dims: 1024

optimizer:
  name: 'Adam'
  kwargs:
    lr: 0.001
    weight_decay: 0.0001

criterion:
  name: 'NTXentLoss'
  temperature: 0.5

training:
  epochs: 100
  validate_every: 1
  checkpoint_every: 5

tensorboard:
  log_dir: 'D:/Ziwei/Github/experiments/tensorboard'

