device: 'cuda'  # or 'cpu' if you do not have a GPU
experiment_dir: '/home/ljd567/datadir/vae_experiment_test/'

data:
  path: '/home/ljd567/datadir/ContrastiveVAE_Data/data_nor.h5'

loader:
  batch_size: 64
  shuffle: True
  num_workers: 32

model:
  name: 'ContrastiveVAE'
  kwargs:
    latent_dim: 128
    projection_dim: 64
    k: 20
    emb_dims: 512  # This is the dimension of the feature space after encoding the point cloud
    num_points: 2048

optimizer:
  name: 'Adam'
  kwargs:
    lr: 0.001
    weight_decay: 0.00001

criterion:
  name: 'NTXentLoss'
  temperature: 0.5

loss_weights:
  Rec_loss: 100
  KLD: 0.1
  contrastive_loss: 1.0

training:
  epochs: 100
  validate_every: 1
  checkpoint_every: 5

tensorboard:
  log_dir: '/home/ljd567/datadir/vae_experiment_test/tensorboard'

use_contrastive_loss: false