device: 'cuda'  # or 'cpu' if you do not have a GPU
experiment_dir: './experiments_1/'

data:
  path: 'D:/Ziwei/Github/data/data_nor.h5'

loader:
  batch_size: 4
  shuffle: True
  num_workers: 8

model:
  name: 'ContrastiveVAE'
  kwargs:
    latent_dim: 128
    projection_dim: 64
    k: 20
    emb_dims: 1024  # This is the dimension of the feature space after encoding the point cloud
    num_points: 2048

optimizer:
  name: 'Adam'
  kwargs:
    lr: 0.001
    weight_decay: 0.0001

criterion:
  name: 'NTXentLoss'
  temperature: 0.5

loss_weights:
  Rec_loss: 1.0
  KLD: 1.0
  contrastive_loss: 1.0

training:
  epochs: 30
  validate_every: 1
  checkpoint_every: 5

tensorboard:
  log_dir: 'D:/Ziwei/Github/experiments/tensorboard'
